### ISSUE TITLE
[BUG] - LTS is 3-year-old

### ISSUE THREAD

**Issue by DamienCassou** [jitesoft/docker-node-yarn#1]
According to the documentation

> Images are built for x86_64 and aarch64 and the latest and lts versions are actively maintained.

however, this is what I see in Dockerhub:

![2024-09-04_15-54](https://github.com/user-attachments/assets/335bcd91-129a-4d65-8b51-713ec7c5ffa8)

The LTS image is 3 year old and contains a very old version of node (time goes very fast in the nodejs world apparently :-D).

I would have expected the LTS image to be fairly recent.

**Comment by Johannestegner** [comment]
Than you for the report!

It seems like there is a small "bug" in the build script where the specific tags get overriden by another variable, I will take a look at this ASAP and fix it.

**Comment by Johannestegner** [comment]
In short, some changes was done with the CI script for the base image that had not propagated through to this image.
Seeing the build still succeeded (but the tag was lost in translation) there was no obvious indication on why this happened.

I have updated the build script to work as intended and also updated readme to be more obvious that the tags are automatically pushed rather than "actively maintained", to show that I don't actually manually push them.


Small remark as well:

The "latest" tag is outdated due to an issue with building Node.js 22 for alpine, something I'm working on. LTS is iron/20 now though. :)

![image](https://github.com/user-attachments/assets/d7c60576-6011-4120-8b48-c4a1310baa4e)

**Comment by DamienCassou** [comment]
Awesome, thank you very much!
